DROP TABLE IF EXISTS brand;

CREATE TABLE brand (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   name VARCHAR(255) NOT NULL UNIQUE,
   description VARCHAR(255),
   logo_url VARCHAR(255) NOT NULL,
   deleted BOOLEAN DEFAULT FALSE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP NULL
);
